// const SEARCH = "SEARCH";
// const SHORTLIST = "SHORTLIST";

const GET_CANDIDATES_REQUEST = "GET_CANDIDATES_REQUEST";
const GET_CANDIDATES_LOADING = "GET_CANDIDATES_LOADING";
const GET_CANDIDATES_FAILURE = "GET_CANDIDATES_FAILURE";
const GET_CANDIDATES_SUCCESS = "GET_CANDIDATES_SUCCESS";

export default {
    // SEARCH,
    // SHORTLIST,

    GET_CANDIDATES_REQUEST,
    GET_CANDIDATES_LOADING,
    GET_CANDIDATES_FAILURE,
    GET_CANDIDATES_SUCCESS
}