// const JOBS_SEARCH = "JOBS_SEARCH";
// const DO_SHORTLIST = "DO_SHORTLIST";

const GET_JOBS_REQUEST = "GET_JOBS_REQUEST";
const GET_JOBS_LOADING = "GET_JOBS_LOADING";
const GET_JOBS_FAILURE = "GET_JOBS_FAILURE";
const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export default {
    // JOBS_SEARCH,
    // DO_SHORTLIST,

    GET_JOBS_REQUEST,
    GET_JOBS_LOADING,
    GET_JOBS_FAILURE,
    GET_JOBS_SUCCESS
}