const SET_CULTURE_ASSESSMENT = "SET_CULTURE_ASSESSMENT";
const CHANGE_CULTURE_ASSESSMENT_PAGE = "CHANGE_CULTURE_ASSESSMENT_PAGE";
const CLEAR_CULTURE_ASSESSMENT = "CLEAR_CULTURE_ASSESSMENT";

const SET_PERSONALITIES_ASSESSMENT = "SET_PERSONALITIES_ASSESSMENT";
const CHANGE_PERSONALITIES_ASSESSMENT_PAGE = "CHANGE_PERSONALITIES_ASSESSMENT_PAGE";
const CLEAR_PERSONALITIES_ASSESSMENT = "CLEAR_PERSONALITIES_ASSESSMENT";

const SET_VALUES_ASSESSMENT = "SET_VALUES_ASSESSMENT";
const CHANGE_VALUES_ASSESSMENT_PAGE = "CHANGE_VALUES_ASSESSMENT_PAGE";
const CLEAR_VALUES_ASSESSMENT = "CLEAR_VALUES_ASSESSMENT";

const CLEAR_ASSESSMENT_REQUEST = "CLEAR_ASSESSMENT_REQUEST";
const CLEAR_ASSESSMENT = "CLEAR_ASSESSMENT";

const SAVE_ASSESSMENT_REQUEST = "SAVE_ASSESSMENT_REQUEST";

export default {
    SET_CULTURE_ASSESSMENT,
    CHANGE_CULTURE_ASSESSMENT_PAGE,
    CLEAR_CULTURE_ASSESSMENT,

    SET_PERSONALITIES_ASSESSMENT,
    CHANGE_PERSONALITIES_ASSESSMENT_PAGE,
    CLEAR_PERSONALITIES_ASSESSMENT,

    SET_VALUES_ASSESSMENT,
    CHANGE_VALUES_ASSESSMENT_PAGE,
    CLEAR_VALUES_ASSESSMENT,

    CLEAR_ASSESSMENT_REQUEST,
    CLEAR_ASSESSMENT,

    SAVE_ASSESSMENT_REQUEST
}