const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const RESET_DATA = "RESET_DATA";

const GET_ME_REQUEST = "GET_ME_REQUEST";
const GET_ME_LOADING = "GET_ME_LOADING";
const GET_ME_SUCCESS = "GET_ME_SUCCESS";
const GET_ME_FAILURE = "GET_ME_FAILURE";

const AUTH_REQUEST = "AUTH_REQUEST";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAILURE = "AUTH_FAILURE";

export default {
    LOGOUT_REQUEST,
    RESET_DATA,

    GET_ME_REQUEST,
    GET_ME_LOADING,
    GET_ME_SUCCESS,
    GET_ME_FAILURE,

    AUTH_REQUEST,
    AUTH_SUCCESS,
    AUTH_FAILURE
}